/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.Collections;
import java.util.Comparator;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class RankingView extends javax.swing.JFrame {

    /**
     * Creates new form RankingView
     */
    public RankingView() {
        initComponents();
    }

    public void setRanking(String received){
        Vector vHeader = new Vector();
        vHeader.add("TOP");
        vHeader.add("User");
        vHeader.add("Score");
        vHeader.add("Win");
        Vector vData = new Vector();
        String[] data = received.split(";");
        int i = -1;
        for(String tmp:data){
            i++;
            if(i == 0){
                continue;
            }
            System.out.println(tmp);
            if(tmp == null){
                break;
            }
            String[] user = tmp.split(",");
            Vector vRow = new Vector();
            vRow.add(Integer.toString(i));
            vRow.add(user[0]);
            vRow.add(user[2]);
            vRow.add(user[3]);
            vData.add(vRow);
        }
        jTableRanking.setModel(new DefaultTableModel(vData, vHeader));
        setRanking1(received);
    }
    
    public void setRanking1(String received){
        Vector vHeader = new Vector();
        vHeader.add("TOP");
        vHeader.add("User");
        vHeader.add("Score");
        vHeader.add("Win");
        Vector<Vector<String>> vData = new Vector<>();
        String[] data = received.split(";");
        int i = -1;
        for(String tmp:data){
            i++;
            if(i == 0){
                continue;
            }
            System.out.println(tmp);
            if(tmp == null){
                break;
            }
            String[] user = tmp.split(",");
            Vector<String> vRow = new Vector<>();
            vRow.add(Integer.toString(i));
            vRow.add(user[0]);
            vRow.add(user[2]);
            vRow.add(user[3]);
            vData.add(vRow);
        }
        
        Collections.sort(vData, new Comparator<Vector<String>>() {
            @Override
            public int compare(Vector<String> v1, Vector<String> v2) {
                int wins1 = Integer.parseInt(v1.get(3)); 
                int wins2 = Integer.parseInt(v2.get(3)); 
                return Integer.compare(wins2, wins1);
            }
        });
        
        int j = 1;
        for(Vector<String> v:vData){
            v.set(0, Integer.toString(j));
            j++;
        }
        
        jTableRanking1.setModel(new DefaultTableModel(vData, vHeader));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRanking = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRanking1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("RANKING");

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jTableRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Top", "User", "Score", "Win"
            }
        ));
        jScrollPane1.setViewportView(jTableRanking);

        jTabbedPane1.addTab("Score", jScrollPane1);

        jTableRanking1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableRanking1);

        jTabbedPane1.addTab("Number of Wins", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RankingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RankingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RankingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RankingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RankingView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableRanking;
    private javax.swing.JTable jTableRanking1;
    // End of variables declaration//GEN-END:variables
}
